openapi: 3.0.0
info:
  title: Food Delivery Company API
  version: 1.0.0
  description: API for managing food delivery and orders.

paths:
  /restaurants:
    get:
      summary: Get a list of available restaurants
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - restaurant_id: 1
                  name: Delicious Bites
                  cuisine: Italian
                  rating: 4.5
                - restaurant_id: 2
                  name: Spicy Delight
                  cuisine: Indian
                  rating: 4.2

  /restaurants/{restaurant_id}/menu:
    get:
      summary: Get the menu of a specific restaurant
      parameters:
        - name: restaurant_id
          in: path
          description: ID of the restaurant to retrieve the menu from
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - item_id: 101
                  name: Margherita Pizza
                  description: Classic pizza with tomato, mozzarella, and basil
                  price: 10.99
                - item_id: 102
                  name: Chicken Tikka Masala
                  description: Grilled chicken cooked in a creamy tomato sauce
                  price: 12.49

  /orders:
    post:
      summary: Place a new food order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                restaurant_id:
                  type: integer
                  description: ID of the selected restaurant
                items:
                  type: array
                  description: List of items in the order
                  items:
                    type: object
                    properties:
                      item_id:
                        type: integer
                      quantity:
                        type: integer
              required:
                - restaurant_id
                - items
      responses:
        '201':
          description: Order successfully placed
        '400':
          description: Invalid input data

  /orders/{order_id}:
    get:
      summary: Get details of a specific order
      parameters:
        - name: order_id
          in: path
          description: ID of the order to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                order_id: 12345
                restaurant_id: 1
                items:
                  - item_id: 101
                    name: Margherita Pizza
                    quantity: 2
                  - item_id: 102
                    name: Chicken Tikka Masala
                    quantity: 1
                total_price: 34.97
                status: "Delivered"
